### ISSUE TITLE
SyntaxError: Unexpected token (

### ISSUE THREAD

**Issue by Meldiron** [Jake-Ruston/fortnite#3]
My script:
```
const fortnite = require('fortnite');

fortnite('NickCannonn', 'pc').then((data) => {
    console.log(data);
});
```

Error:
```
/Users/Meldiron/Desktop/fornite/node_modules/fortnite/src/Client.js:14
  return new Promise(async (resolve, reject) => {
                           ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Meldiron/Desktop/fornite/node_modules/fortnite/index.js:1:80)
```

NodeJS version: v6.10.3
NPM version: 5.5.1
Fornite (your library) version: ^2.0.1

**Comment by Jake-Ruston** [comment]
Firstly sorry for the late reply. You will need to update your NodeJS version to at least [v8](https://nodejs.org/en/download/).
